Feature/0.4.0 catchup
KMU-quantum-classroom/qiskit-classroom pull request #11
Opened 2023-10-12 01:56 UTC by fmowl10

* Update dependency 
  * from qiskit-classroom-converter 0.3.0 to qiskit-classroom-converter 0.4.0
* use /tmp for snap packages or flatpak packages
* Chnage Visualiazation code
  * underscore to stackrel 

from
```latex
\begin{bmatrix}
0 & 1 & 0 & 0  \\
0 & 0 & 1 & 0  \\
0 & 0 & 0 & 1  \\
1 & 0 & 0 & 0  \\
\end{bmatrix}_{ddd}
``` 
to 
```latex
\stackrel{hey}{
\begin{bmatrix}
0 & 1 & 0 & 0  \\
 0 & 0 & 1 & 0  \\
 0 & 0 & 0 & 1  \\
 1 & 0 & 0 & 0  \\
 \end{bmatrix}
}
```

2023-10-12 02:13 UTC, minwook-shin requested changes

2023-10-12 02:13 UTC, minwook-shin commented on qiskit_classroom/converter_presenter.py
> +            print(exc)
로그로 남게 로깅 메시지로 바꾸거나, 프린트문 제거하는 게 좋아보입니다.

2023-10-12 02:14 UTC, fmowl10 commented on qiskit_classroom/converter_presenter.py
> +            print(exc)
다이얼로그에 붙이는 식으로 바꾸겠습니다.

2023-10-15 09:07 UTC, minwook-shin approved these changes

2023-10-15 09:08 UTC, merged